WIP: none of these kernels work when replotting res_objective
same error from skopt/learning/gaussian_process/gpr.py:
    grad = self.kernel_.gradient_x(X[0], self.X_train_)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Sum' object has no attribute 'gradient_x'

... does skopt gpr class need to add this method or is it inherited?